import Header from "./Header"
import Banner from "./Banner"
import About from "./About"
import Specilizing from "./Specilizing"
import Project from "./Project"
import Education from "./Education"
import CaseStudy from "./CaseStudy"
import Footer from "./Footer"
import ContactMe from "./ContactMe"
export { Header, Banner, About, Specilizing, Project, Education, CaseStudy, Footer,ContactMe }
